platform: linux
inputs:
- name: tree
outputs:
- name: dist
run:
  path: sh
  args:
  - -exc
  - |
    ./waf configure --debug --prefix=/tmp install
    ./waf dist
    cp oregano-*.tar.xz ../dist/
  dir: tree
